### ISSUE TITLE
Missing code LICENSE

### ISSUE THREAD

**Issue by JJRcop** [taskinoz/RSPNVPK#1]
This entire codebase is missing copyright ownership information and/or a software license.

I understand it may be tricky to include one because you are not the original author (would probably have to contact mrsteyk), but protecting yourself and protecting the code should be at least given consideration.

**https://choosealicense.com/**

**Comment by taskinoz** [comment]
I've asked Mrsteyk and he said he wanted a MIT license so I've added it here
ec37100187b00f91b17365b7b7f9ebce4c89b4e4
