### ISSUE TITLE
Still asking me to backup when I use "-b"

### ISSUE THREAD

**Issue by VictoriousRaptor** [taskinoz/RSPNVPK#3]
There's no need to ask whether a user wants a backup when he uses the "-b" arg.

**Comment by taskinoz** [comment]
I'll look into it, but I think I can make a quick fix for that

**Comment by VictoriousRaptor** [comment]
I don't want to create a fork. Just add `silent = true;` in `Program.cs:88` and should be fine.

**Comment by taskinoz** [comment]
-b should be silent in v1.2.9 now.

https://github.com/taskinoz/RSPNVPK/releases/tag/v1.2.9
